name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            wget \
            build-essential \
            libffi-dev \
            libssl-dev \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            cmake

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
          pip install cython==0.29.33

      - name: Install Android SDK
        run: |
          mkdir -p "$HOME/android-sdk/cmdline-tools"

          cd "$HOME"

          wget -q https://dl.google.com/android/repository/commandlinetools-linux-15859902_latest.zip

          unzip -q commandlinetools-linux-15859902_latest.zip

          mv cmdline-tools "$HOME/android-sdk/cmdline-tools/latest"

          echo "ANDROID_HOME=$HOME/android-sdk" >> "$GITHUB_ENV"
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> "$GITHUB_ENV"
          echo "ANDROIDSDK=$HOME/android-sdk" >> "$GITHUB_ENV"

          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> "$GITHUB_PATH"
          echo "$HOME/android-sdk/platform-tools" >> "$GITHUB_PATH"

      - name: Check SDK Manager
        run: |
          which sdkmanager
          sdkmanager --version

      - name: Accept Android SDK licenses
        run: |
          yes | sdkmanager --sdk_root="$HOME/android-sdk" --licenses || true

      - name: Install Android SDK packages
        run: |
          sdkmanager --sdk_root="$HOME/android-sdk" \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0" \
  

      - name: Verify AIDL
        run: |
          echo "Checking AIDL..."

          ls -la "$HOME/android-sdk/build-tools/35.0.0/aidl"
          ls -la "$HOME/android-sdk/build-tools/37.0.0/aidl"

          "$HOME/android-sdk/build-tools/37.0.0/aidl" --version

          echo "AIDL OK"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: bin/*.apk
